apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nosql
  name: nosql
  namespace: haddock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nosql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nosql
    spec:
      containers:
      - image: hub.atomgit.com/amd64/nginx:1.25.2
        name: nginx
        resources:
          limits: 
            memory: 2000Mi
          requests:
            memory: 2000Mi
