apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: ckad00015
spec:
  replicas: 10
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: hub.atomgit.com/amd64/nginx:1.24
        name: nginx
        resources: {}
