apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ckad00018-newpod
  name: ckad00018-newpod
  namespace: ckad00018
spec:
  containers:
  - image: hub.atomgit.com/amd64/busybox:1.35
    name: ckad00018-newpod
    command:
    - /bin/sh
    - -c
    - "sleep 1d"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
