apiVersion: v1
kind: Pod
metadata:
  labels:
    run: probe-demo
  name: probe-demo
  namespace: probe-ns
spec:
  containers:
  - name: probe-demo
    image: hub.atomgit.com/amd64/nginx:1.25
    ports:
    - name: http
      protocol: TCP   # UDP
      containerPort: 80  # 声明pod中的这个容器监听的端口
    livenessProbe:
      tcpSocket:
        port: 81
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
  dnsPolicy: ClusterFirst
  hostNetwork: false
  restartPolicy: Always
